name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

permissions:
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      issue-number: ${{ steps.vars.outputs.issue-number }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: package.json
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm run test
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: dist
          path: dist
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: action.yml
          path: action.yml
      - id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then \
            echo "issue-number=${{ github.event.number }}" >> $GITHUB_OUTPUT; \
          else \
            echo "issue-number=1" >> $GITHUB_OUTPUT; \
          fi

  test:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [built, committed]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: dist
          path: dist
      - if: matrix.target == 'built' || github.event_name == 'pull_request'
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: action.yml
          path: .

      - name: Test create comment
        uses: ./
        id: couc
        with:
          issue-number: ${{ needs.build.outputs.issue-number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/step-security/create-or-update-comment
          reactions: '+1'

      - name: Test update comment
        uses: ./
        with:
          comment-id: ${{ steps.couc.outputs.comment-id }}
          body: |
            **Edit:** Some additional info
          reactions: eyes
          reactions-edit-mode: replace

      - name: Test add reactions
        uses: ./
        with:
          comment-id: ${{ steps.couc.outputs.comment-id }}
          reactions: |
            heart
            hooray
            laugh

      - name: Test create comment from file
        uses: ./
        id: couc2
        with:
          issue-number: ${{ needs.build.outputs.issue-number }}
          body-path: .github/comment-body.md
          reactions: |
            +1

      - name: Test update comment from file
        uses: ./
        with:
          comment-id: ${{ steps.couc2.outputs.comment-id }}
          body-path: .github/comment-body-addition.md
          append-separator: space
          reactions: eyes, rocket
          reactions-edit-mode: replace
